import { useRef, useState, useMemo, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Upload, X, Check, Copy, Search, Loader2, FileText, Image as ImageIcon,
  File, Sparkles, Trash2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import {
  assetService, ASSET_TYPE_META, ASSET_CATEGORIES,
  type AssetType, type AssetCategory, type Asset,
} from "@/services/assetService";

const BUCKET = "book-images";

// ── Auto-detect asset type from file ──
function detectType(file: File): AssetType {
  const ext = file.name.split(".").pop()?.toLowerCase() || "";
  const name = file.name.toLowerCase();

  if (/(card|carte|بطاقة|بطاقات)/.test(name)) return "CRD";
  if (/(flyer|فلاير|flayer)/.test(name)) return "FLY";
  if (/(poster|ملصق|affiche)/.test(name)) return "PST";
  if (/(logo|شعار)/.test(name)) return "LOG";
  if (/(template|قالب|قوالب)/.test(name)) return "TPL";
  if (/(menu|قائمة|قوائم)/.test(name)) return "LST";
  if (/(art|فن|artwork)/.test(name)) return "ART";

  if (["psd", "ai", "indd", "eps"].includes(ext)) return "TPL";
  if (["svg"].includes(ext)) return "LOG";
  if (["pptx", "ppt", "key"].includes(ext)) return "PRE";
  if (["pdf", "docx", "doc", "txt", "rtf"].includes(ext)) return "DOC";
  if (["jpg", "jpeg", "png", "webp", "tiff", "bmp", "gif"].includes(ext)) return "IMG";
  return "OTH";
}

function previewYearSeq(year: number): string {
  // visual placeholder — actual seq generated by DB trigger
  return `${year}-?????`;
}

function buildPreviewCode(type: AssetType): string {
  const cat = ASSET_TYPE_META[type].category;
  const year = new Date().getFullYear();
  return `HN-${cat}-${type}-${previewYearSeq(year)}`;
}

function cleanTitle(filename: string): string {
  return filename.replace(/\.[^.]+$/, "").replace(/[-_]+/g, " ").trim();
}

interface PendingItem {
  id: string;
  file: File;
  title: string;
  type: AssetType;
  previewUrl: string;
  isImage: boolean;
  uploading: boolean;
  progress: number;
}

const SmartImportPage = () => {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [pending, setPending] = useState<PendingItem[]>([]);
  const [savedAssets, setSavedAssets] = useState<Asset[]>([]);
  const [loadingList, setLoadingList] = useState(true);
  const [search, setSearch] = useState("");
  const [filterCategory, setFilterCategory] = useState<AssetCategory | "all">("all");
  const [filterType, setFilterType] = useState<AssetType | "all">("all");

  // Load saved assets
  useEffect(() => {
    void loadAssets();
  }, []);

  const loadAssets = async () => {
    setLoadingList(true);
    try {
      const list = await assetService.list({ limit: 100 });
      setSavedAssets(list);
    } catch (e: any) {
      toast.error(`فشل تحميل الأصول: ${e.message}`);
    } finally {
      setLoadingList(false);
    }
  };

  // ── File handling ──
  const addFiles = (files: File[]) => {
    if (!files.length) return;
    const items: PendingItem[] = files.map((file) => {
      const type = detectType(file);
      const isImage = file.type.startsWith("image/");
      return {
        id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
        file,
        title: cleanTitle(file.name),
        type,
        previewUrl: isImage ? URL.createObjectURL(file) : "",
        isImage,
        uploading: false,
        progress: 0,
      };
    });
    setPending((prev) => [...items, ...prev]);
    toast.info(`📥 ${items.length} ملف جاهز للمعاينة`);
  };

  const updatePending = (id: string, patch: Partial<PendingItem>) =>
    setPending((prev) => prev.map((p) => (p.id === id ? { ...p, ...patch } : p)));

  const removePending = (id: string) => {
    setPending((prev) => {
      const item = prev.find((p) => p.id === id);
      if (item?.previewUrl) URL.revokeObjectURL(item.previewUrl);
      return prev.filter((p) => p.id !== id);
    });
  };

  // ── Save asset ──
  const saveAsset = async (item: PendingItem) => {
    updatePending(item.id, { uploading: true, progress: 10 });
    try {
      const ext = item.file.name.split(".").pop()?.toLowerCase() || "bin";
      const safeKey = `assets/${item.type}/${Date.now()}-${Math.random().toString(36).slice(2, 8)}.${ext}`;

      updatePending(item.id, { progress: 40 });
      const { error: upErr } = await supabase.storage
        .from(BUCKET)
        .upload(safeKey, item.file, { cacheControl: "3600", upsert: false });
      if (upErr) throw upErr;

      updatePending(item.id, { progress: 70 });
      const { data: pub } = supabase.storage.from(BUCKET).getPublicUrl(safeKey);
      const fileUrl = pub.publicUrl;
      const imageUrl = item.isImage ? fileUrl : "/placeholder.svg";

      const created = await assetService.create({
        asset_type: item.type,
        title: item.title.trim() || cleanTitle(item.file.name),
        image_url: imageUrl,
        file_url: fileUrl,
      });

      updatePending(item.id, { progress: 100 });
      toast.success(`✅ تم الحفظ — ${created.code}`);
      removePending(item.id);
      setSavedAssets((prev) => [created, ...prev]);
    } catch (e: any) {
      toast.error(`❌ فشل الحفظ: ${e.message}`);
      updatePending(item.id, { uploading: false, progress: 0 });
    }
  };

  const saveAll = async () => {
    for (const item of [...pending]) {
      if (!item.uploading) await saveAsset(item);
    }
  };

  // ── Filtered table ──
  const filtered = useMemo(() => {
    return savedAssets.filter((a) => {
      if (filterCategory !== "all" && a.category !== filterCategory) return false;
      if (filterType !== "all" && a.asset_type !== filterType) return false;
      if (search) {
        const s = search.toLowerCase();
        if (!a.code?.toLowerCase().includes(s) && !a.title.toLowerCase().includes(s)) return false;
      }
      return true;
    });
  }, [savedAssets, search, filterCategory, filterType]);

  const copyCode = async (code: string) => {
    await navigator.clipboard.writeText(code);
    toast.success(`📋 ${code}`);
  };

  const deleteAsset = async (id: string) => {
    if (!confirm("حذف هذا الأصل؟")) return;
    try {
      await assetService.remove(id);
      setSavedAssets((prev) => prev.filter((a) => a.id !== id));
      toast.success("تم الحذف");
    } catch (e: any) {
      toast.error(e.message);
    }
  };

  return (
    <div className="space-y-6" dir="rtl">
      {/* Header */}
      <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}>
        <h1 className="text-2xl font-extrabold text-foreground flex items-center gap-2">
          <Sparkles className="w-6 h-6 text-primary" /> الاستيراد الذكي
        </h1>
        <p className="text-sm text-muted-foreground mt-1">
          ارفع أي ملف — كشف تلقائي للنوع، توليد كود فوري، معاينة قبل الحفظ
        </p>
      </motion.div>

      {/* Drop zone */}
      <div
        onDragOver={(e) => e.preventDefault()}
        onDrop={(e) => { e.preventDefault(); addFiles(Array.from(e.dataTransfer.files)); }}
        onClick={() => fileInputRef.current?.click()}
        className="cursor-pointer rounded-2xl border-2 border-dashed border-border hover:border-primary/60 bg-card/50 p-10 flex flex-col items-center justify-center gap-3 transition-colors"
      >
        <Upload className="w-10 h-10 text-muted-foreground" />
        <p className="text-sm font-medium text-foreground">اسحب الملفات أو اضغط لاختيارها</p>
        <p className="text-xs text-muted-foreground">صور، PDF، PSD، AI، SVG، PPTX، DOCX...</p>
      </div>
      <input
        ref={fileInputRef} type="file" multiple accept="*/*"
        onChange={(e) => { addFiles(Array.from(e.target.files || [])); e.target.value = ""; }}
        className="hidden"
      />

      {/* Pending preview cards */}
      <AnimatePresence>
        {pending.length > 0 && (
          <motion.div
            initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}
            className="space-y-3"
          >
            <div className="flex items-center justify-between">
              <h2 className="text-sm font-bold text-foreground">📋 معاينة قبل الحفظ ({pending.length})</h2>
              <div className="flex gap-2">
                <Button size="sm" onClick={saveAll} className="gap-1">
                  <Check className="w-4 h-4" /> حفظ الكل
                </Button>
                <Button size="sm" variant="ghost" onClick={() => { pending.forEach((p) => p.previewUrl && URL.revokeObjectURL(p.previewUrl)); setPending([]); }}>
                  إلغاء الكل
                </Button>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
              {pending.map((item) => {
                const meta = ASSET_TYPE_META[item.type];
                const previewCode = buildPreviewCode(item.type);
                return (
                  <motion.div
                    key={item.id}
                    layout
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.9 }}
                    className="rounded-xl border border-border bg-card overflow-hidden"
                  >
                    {/* Preview */}
                    <div className="aspect-video bg-muted flex items-center justify-center relative">
                      {item.isImage ? (
                        <img src={item.previewUrl} alt={item.title} className="w-full h-full object-cover" />
                      ) : (
                        <div className="flex flex-col items-center gap-2 text-muted-foreground">
                          <FileText className="w-12 h-12" />
                          <span className="text-xs">{item.file.name.split(".").pop()?.toUpperCase()}</span>
                        </div>
                      )}
                      <button
                        onClick={() => removePending(item.id)}
                        disabled={item.uploading}
                        className="absolute top-2 left-2 w-7 h-7 rounded-full bg-background/90 hover:bg-destructive hover:text-destructive-foreground flex items-center justify-center transition-colors"
                      >
                        <X className="w-4 h-4" />
                      </button>
                    </div>

                    {/* Body */}
                    <div className="p-3 space-y-3">
                      {/* Generated code */}
                      <div className="rounded-lg bg-primary/10 border border-primary/30 p-2.5 text-center">
                        <p className="text-[10px] text-muted-foreground mb-1">الكود التلقائي</p>
                        <p className="font-mono text-sm font-bold text-primary tracking-tight">
                          {previewCode}
                        </p>
                      </div>

                      {/* Type / Category */}
                      <div className="flex gap-2">
                        <Select
                          value={item.type}
                          onValueChange={(v) => updatePending(item.id, { type: v as AssetType })}
                          disabled={item.uploading}
                        >
                          <SelectTrigger className="h-8 text-xs flex-1">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            {(Object.keys(ASSET_TYPE_META) as AssetType[]).map((t) => (
                              <SelectItem key={t} value={t} className="text-xs">
                                {ASSET_TYPE_META[t].emoji} {ASSET_TYPE_META[t].label} ({t})
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                        <Badge variant="outline" className="text-[10px] flex items-center px-2">
                          {ASSET_CATEGORIES[meta.category]}
                        </Badge>
                      </div>

                      {/* Title */}
                      <Input
                        value={item.title}
                        onChange={(e) => updatePending(item.id, { title: e.target.value })}
                        placeholder="العنوان"
                        disabled={item.uploading}
                        className="h-8 text-xs"
                      />

                      {/* Progress */}
                      {item.uploading && (
                        <div className="space-y-1">
                          <Progress value={item.progress} className="h-1.5" />
                          <p className="text-[10px] text-muted-foreground text-center">
                            {item.progress < 100 ? `جاري الرفع... ${item.progress}%` : "تم"}
                          </p>
                        </div>
                      )}

                      {/* Actions */}
                      <div className="flex gap-2">
                        <Button
                          size="sm"
                          onClick={() => saveAsset(item)}
                          disabled={item.uploading || !item.title.trim()}
                          className="flex-1 h-8 text-xs gap-1"
                        >
                          {item.uploading ? <Loader2 className="w-3 h-3 animate-spin" /> : <Check className="w-3 h-3" />}
                          حفظ
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => removePending(item.id)}
                          disabled={item.uploading}
                          className="h-8 text-xs"
                        >
                          إلغاء
                        </Button>
                      </div>
                    </div>
                  </motion.div>
                );
              })}
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Saved table */}
      <div className="space-y-3">
        <div className="flex flex-col md:flex-row gap-2 items-stretch md:items-center justify-between">
          <h2 className="text-sm font-bold text-foreground">
            📚 الأصول المحفوظة ({filtered.length})
          </h2>
          <div className="flex flex-wrap gap-2">
            <div className="relative flex-1 min-w-[180px]">
              <Search className="absolute right-2 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-muted-foreground" />
              <Input
                placeholder="بحث بالكود أو العنوان..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="h-8 text-xs pr-8"
              />
            </div>
            <Select value={filterCategory} onValueChange={(v) => setFilterCategory(v as any)}>
              <SelectTrigger className="h-8 text-xs w-[120px]"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="all" className="text-xs">كل الفئات</SelectItem>
                {(Object.keys(ASSET_CATEGORIES) as AssetCategory[]).map((c) => (
                  <SelectItem key={c} value={c} className="text-xs">{ASSET_CATEGORIES[c]} ({c})</SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Select value={filterType} onValueChange={(v) => setFilterType(v as any)}>
              <SelectTrigger className="h-8 text-xs w-[120px]"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="all" className="text-xs">كل الأنواع</SelectItem>
                {(Object.keys(ASSET_TYPE_META) as AssetType[]).map((t) => (
                  <SelectItem key={t} value={t} className="text-xs">
                    {ASSET_TYPE_META[t].emoji} {ASSET_TYPE_META[t].label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>

        <div className="rounded-2xl border border-border bg-card overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="bg-muted/50 text-xs text-muted-foreground">
                <tr>
                  <th className="text-right p-3 font-medium">معاينة</th>
                  <th className="text-right p-3 font-medium">الكود</th>
                  <th className="text-right p-3 font-medium">العنوان</th>
                  <th className="text-right p-3 font-medium">النوع</th>
                  <th className="text-right p-3 font-medium">الفئة</th>
                  <th className="text-right p-3 font-medium">التاريخ</th>
                  <th className="p-3" />
                </tr>
              </thead>
              <tbody className="divide-y divide-border/50">
                {loadingList ? (
                  <tr><td colSpan={7} className="p-8 text-center text-muted-foreground">
                    <Loader2 className="w-5 h-5 animate-spin inline" />
                  </td></tr>
                ) : filtered.length === 0 ? (
                  <tr><td colSpan={7} className="p-8 text-center text-muted-foreground text-xs">
                    لا توجد أصول بعد
                  </td></tr>
                ) : (
                  filtered.map((a) => {
                    const meta = ASSET_TYPE_META[a.asset_type as AssetType];
                    return (
                      <tr key={a.id} className="hover:bg-muted/30 transition-colors">
                        <td className="p-2">
                          <div className="w-12 h-12 rounded-lg bg-muted overflow-hidden flex items-center justify-center">
                            {a.image_url && a.image_url !== "/placeholder.svg" ? (
                              <img src={a.image_url} alt={a.title} className="w-full h-full object-cover" />
                            ) : (
                              <File className="w-5 h-5 text-muted-foreground" />
                            )}
                          </div>
                        </td>
                        <td className="p-2">
                          <button
                            onClick={() => copyCode(a.code)}
                            className="font-mono text-xs px-2 py-1 rounded bg-primary/10 text-primary hover:bg-primary/20 inline-flex items-center gap-1"
                          >
                            {a.code} <Copy className="w-3 h-3" />
                          </button>
                        </td>
                        <td className="p-2 text-foreground text-xs max-w-[200px] truncate">{a.title}</td>
                        <td className="p-2">
                          <Badge variant="secondary" className="text-[10px]">
                            {meta?.emoji} {meta?.label || a.asset_type}
                          </Badge>
                        </td>
                        <td className="p-2 text-xs text-muted-foreground">
                          {ASSET_CATEGORIES[a.category as AssetCategory] || a.category}
                        </td>
                        <td className="p-2 text-[10px] text-muted-foreground whitespace-nowrap">
                          {new Date(a.created_at).toLocaleDateString("ar-MA")}
                        </td>
                        <td className="p-2">
                          <Button size="sm" variant="ghost" onClick={() => deleteAsset(a.id)} className="h-7 w-7 p-0">
                            <Trash2 className="w-3.5 h-3.5 text-destructive" />
                          </Button>
                        </td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SmartImportPage;
