-- Generated files registry: link database records to file storage paths.
-- Used by the file integration layer to track every PDF/SVG/PNG/etc.
-- generated by the platform.

CREATE TABLE IF NOT EXISTS generated_files (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source_table    TEXT NOT NULL,        -- e.g. 'products', 'svg_templates'
  source_id       UUID NOT NULL,        -- the row this file belongs to
  file_kind       TEXT NOT NULL,        -- 'pdf' | 'cover' | 'svg' | 'preview' | ...
  file_name       TEXT NOT NULL,
  storage_path    TEXT NOT NULL,        -- bucket path or VPS path
  public_url      TEXT,
  file_size       BIGINT,
  mime_type       TEXT,
  checksum        TEXT,
  metadata        JSONB NOT NULL DEFAULT '{}'::jsonb,
  generated_by    TEXT,                 -- 'system' | 'user' | edge-function name
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_generated_files_source
  ON generated_files(source_table, source_id);
CREATE INDEX IF NOT EXISTS idx_generated_files_kind
  ON generated_files(file_kind);
